### ISSUE TITLE
Plugin update

### ISSUE THREAD

**Issue by Berisch** [maxisoft/ASFFreeGames#101]
Hey!
Not sure if this is the correct place to ask this, but wnated to clarify how can I update the plugin?
Only by re-downloading and replacing the .dll file manually?
Or is it possible to update using updateplugins [command](https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Commands)?

**Comment by Berisch** [comment]
Forgot to include my results for trying the updateplugins command:
>
updateplugins stable ASFFreeGamesPlugin
<
<ASF> Не удалось! Ничего не найдено!  (failed! Nothing found)
>
updateplugins stable
<
<ASF> Успешно! Ничего не найдено! (success! Nothing found)
>
updateplugins
<
<ASF> Успешно! Ничего не найдено! (success! Nothing found)
>
updateplugins stable ASFFreeGames
<
<ASF> Не удалось! Ничего не найдено! (failed! Nothing found!)

**Comment by maxisoft** [comment]
Hello,

Thank you for bringing this to my attention. You're absolutely right that the current method for updating the ASFFreeGamesPlugin involves manually downloading the latest release and replacing the DLL file. This can be inconvenient, and I understand your desire to use the `updateplugins` command for a more streamlined process.

I'm happy to inform you that I'm actively exploring ways to make the ASFFreeGamesPlugin compatible with the `updateplugins` command. This would involve implementing the [`IGitHubPluginUpdates` interface](https://github.com/JustArchiNET/ArchiSteamFarm/blob/f2b8897ed1344b0b82dfe06850b97d59f8c11d07/ArchiSteamFarm/Plugins/Interfaces/IGitHubPluginUpdates.cs#L46).

While I can't provide a specific timeframe at this moment, I'm committed to making this update a reality. In the meantime, here are the steps you can follow to manually update the plugin:

1. Visit the ASFFreeGamesPlugin releases page
2. Download the latest DLL file that corresponds to your ArchiSteamFarm version.
3. Close ArchiSteamFarm if it's running.
4. Replace the existing ASFFreeGamesPlugin.dll file in your ArchiSteamFarm plugins directory with the downloaded one.
5. Restart ArchiSteamFarm.

I appreciate your patience and understanding. I'll keep you updated on the progress towards `updateplugins` compatibility for the ASFFreeGamesPlugin.

**Comment by maxisoft** [comment]
I'm happy to announce that automatic update checks via GitHub have been implemented for the ASFFreeGames Plugin in the latest release (v1.8.0)! 

While this feature maybe disabled by default (by ASF), you can now leverage it to keep your plugin up-to-date. To enable automatic updates, follow these steps:

1. **Update your ASFFreeGames Plugin:** Download and install the latest version (v1.8.0) from the releases page
2. **Modify your ArchiSteamFarm configuration:** Refer to the ArchiSteamFarm wiki page on `PluginsUpdateList` for detailed instructions ([ArchiSteamFarm wiki](https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Configuration#pluginsupdatelist)):
    - This property allows you to define which plugins (including ASFFreeGames) are considered for automatic updates.

for reference, minimal `ASF.json` config to allow autoupdate looks like:
```json
{
  "PluginsUpdateList": [
    "ASFFreeGames"
  ]
}
```

I hope this update proves helpful! Please don't hesitate to reach out if you have any further questions.
