### ISSUE TITLE
Free to play check doesn't ever match

### ISSUE THREAD

**Issue by Faustvii** [maxisoft/ASFFreeGames#16]
**Describe the bug**
The regex capture group for permanently free doesn't ever match.

See here https://regex101.com/r/pPlxfe/2

This means the check on line [ASFFreeGamesPlugin.cs#235](https://github.com/maxisoft/ASFFreeGames/blob/main/ASFFreeGames/ASFFreeGamesPlugin.cs#L235) never matches.

**Expected behavior**
I would expect it to not redeem permanently free games or be configurable if that's possible with plugins.

**Comment by maxisoft** [comment]
Hey,
Thank for the report, indeed the regex is buggy on the f2p (free to play) part.

As you pointed fixing the regex is going to activate the check [ASFFreeGamesPlugin.cs#235](https://github.com/maxisoft/ASFFreeGames/blob/main/ASFFreeGames/ASFFreeGamesPlugin.cs#L235). BTW I think that adding f2p games should be the default behavior (eg a previously f2p game is going to be non free) of this plugin.

I'll try to add an option/config file to configure this behavior.
