### ISSUE TITLE
Incompatibility of plugin version 1.4.0 with ASF 5.4.12.5

### ISSUE THREAD

**Issue by Rekandy** [maxisoft/ASFFreeGames#43]
**Error Description**
Problem with launching the latest version of the plugin

**To Reproduce**
1.Installing plugin version 1.4.0
2.Running ASF and getting an error that indicates that all other plugins are not working(of course, when you remove the plugin all starts to work fine).

**Expected behavior**
Running the programme with all plug-ins

**Screenshots**
![ArchiSteamFarm_RLpx8lfgPN](https://github.com/maxisoft/ASFFreeGames/assets/77551516/e9362f78-434f-4162-8be6-11154f4904df)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 1.4.0

**Comment by maxisoft** [comment]
Thank you for reporting this issue. 👍

## About the error
I have acknowledged the issue and found out that it is related to the trimming of the ASF binary, which removes some methods that are not used by the main program.  
One of these methods is the [Lazy<T>(T)](https://learn.microsoft.com/en-us/dotnet/api/system.lazy-1.-ctor?view=net-7.0#system-lazy-1-ctor(-0)) constructor that takes a value parameter, which was used by the PluginContext class. This causes a `System.MissingMethodException` when the plugin start and tries to access it.

## Solutions
- I will create a new release soon with a fix that avoids using the trimmed method.  
- In the meantime, I have marked the 1.4.0 version as pre-release to prevent users from seeing it on the main GitHub page. I apologize for any inconvenience this may have caused.
- I am also working on fixing the integration tests to prevent these kind of issues from happening again.

----
Thank you for your patience and understanding. Have a nice day! 😊

**Comment by maxisoft** [comment]
issue should be resolved with latest release https://github.com/maxisoft/ASFFreeGames/releases/tag/v1.4.1.
