### ISSUE TITLE
ASFFreeGames V1.3.0.0 crashes ASF when looking for free games.

### ISSUE THREAD

**Issue by TheSparkyGhost** [maxisoft/ASFFreeGames#52]
**The fatal errors I get with V1.3.0.0, causing ASF to immediately shutdown.**
-
 **Here are the errors I get when ArchiSteamFarm is first loaded using ASFreeGames.**
------------------------------------
![asffarmerror00](https://github.com/maxisoft/ASFFreeGames/assets/135796876/f9ecac14-f2a8-4dbb-ac2b-90a9f2030030)

**This is the error it gives just before ArchiSteamFarm immediately closes itself.**
------------------------------------
![asffarmerror01](https://github.com/maxisoft/ASFFreeGames/assets/135796876/a9041132-2e2f-473a-8e7c-d73dee1a6eb8)

**I have two bots loaded.. this worked until about a week ago, the program now closes just as soon as it searches for free games. I'm on Windows 11, using ASF V5.5.0.11, and ASFFreeGames V1.3.0.0.**
-

**Comment by TheButterbrotMan** [comment]
Anyone who can update this? :(

**Comment by SirDanielFTW** [comment]
ASF got updated to v6.0.0.3 ... Thats why the plugin doesn't work anymore.

**Comment by maxisoft** [comment]
Hey folks,

Issue #52 is now resolved with the latest plugin update (PR #65). ASF should no longer crash when looking for free games. Make sure to grab the new version 1.5.1 and you'll be set.

Big thanks to everyone for your patience and for flagging up the problem.

Cheers,
Maxisoft
