### ISSUE TITLE
Question: Does this redeem steam game keys, or just games that are already free?

### ISSUE THREAD

**Issue by whatisgithublol1** [maxisoft/ASFFreeGames#79]
Question: Does this redeem steam game keys, or just games that are already free?

**Comment by maxisoft** [comment]
ASFFreeGames is designed to automatically claim games that become or is already free to play on the Steam store. It does not have the functionality to redeem Steam game keys.

If you're looking for a tool to automatically redeem Steam keys, ASFFreeGames is not the right solution.

Please let me know if you have any other questions.
